version: '3'

services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database