# Generated by Django 2.2.10 on 2020-03-04 13:22

from django.db import migrations


def create_content(apps, b):
    from mykiapp.models import ACCESS_LEVELS
    Employee = apps.get_model('mykiapp', 'Employee')
    Team = apps.get_model('mykiapp', 'Team')
    Item = apps.get_model('mykiapp', 'Item')
    Folder = apps.get_model('mykiapp', 'Folder')
    TeamItemAccess = apps.get_model('mykiapp', 'TeamItemAccess')
    TeamFolderAccess = apps.get_model('mykiapp', 'TeamFolderAccess')
    EmployeeItemAccess = apps.get_model('mykiapp', 'EmployeeItemAccess')
    EmployeeFolderAccess = apps.get_model('mykiapp', 'EmployeeFolderAccess')

    item1 = Item.objects.create(name="AWS Credentials", description="Aws Credentials file")
    folder1 = Folder.objects.create(name="Security Related", description="Security Files")
    folder1.items.add(item1)

    item2 = Item.objects.create(name="Team Photo", description="Team photo")
    item3 = Item.objects.create(name="Lunch Menu", description="Lunch menu")
    folder2 = Folder.objects.create(name="Photos", description="Photos")
    folder2.items.add(item2, item3)

    employee1 = Employee.objects.create(first_name="Hassan", last_name="Hammoud")
    employee2 = Employee.objects.create(first_name="Connor", last_name="Makhlouta")
    employee3 = Employee.objects.create(first_name="Luna", last_name="Myki")
    employee4 = Employee.objects.create(first_name="Employee", last_name="myki")

    team1 = Team.objects.create(name="Backend Developers")
    team1.employees.add(employee1, employee2)
    TeamFolderAccess.objects.create(team=team1, folder=folder1, access_level=2)
    EmployeeItemAccess.objects.create(employee=employee1, item=item1, access_level=1)

    team2 = Team.objects.create(name="Management")
    team2.employees.add(employee3)
    TeamFolderAccess.objects.create(team=team2, folder=folder2, access_level=1)
    EmployeeItemAccess.objects.create(employee=employee3, item=item2, access_level=2)
    EmployeeFolderAccess.objects.create(employee=employee4, folder=folder2, access_level=2)


class Migration(migrations.Migration):
    dependencies = [
        ('mykiapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_content)
    ]
